apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: 703674122474.dkr.ecr.us-east-1.amazonaws.com/my-react-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-service
spec:
  type: LoadBalancer
  selector:
    app: my-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
